In [1]:
!pip install numpy


In [4]:
from numpy._typing._shape import _AnyShape
from numpy import dtype
from typing import Any


import numpy as np

## Create 1d array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type[_AnyShape, dtype[Any]](arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)


array([[1, 2, 3, 4, 5]])

In [ ]:
## 2d array
arr3=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr3)
arr3.shape


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

In [11]:
np.arange(0,10,2).reshape(5,1)


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
## identity matrix
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
## Numpy vectorized operations
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

## elementwise operations
print("Addition: ",arr1+arr2)
## Elementwise multiplication
print("Multiplication: ",arr1*arr2)
## Subtraction
print("Subtraction: ",arr2-arr1)
## Division
print("Division: ",arr2/arr1)



Addition:  [11 22 33 44 55]
Multiplication:  [ 10  40  90 160 250]
Subtraction:  [ 9 18 27 36 45]
Division:  [10. 10. 10. 10. 10.]


In [17]:
# universal functions
np.sqrt(arr1)
np.exp(arr1)
print(np.sin(arr1))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [18]:
print(np.log(arr1))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [20]:
## Slicing and indexing
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [21]:
print(arr[0][0])

1


In [22]:
print(arr[1:,2:])

[[ 6]
 [ 9]
 [12]]


In [23]:
print(arr[0:2])

[[1 2 3]
 [4 5 6]]


In [28]:
print(arr[1:2,1:3])

[[5 6]]


In [29]:
print(arr[1:3,0:2])

[[4 5]
 [7 8]]


In [30]:
## Statistical operations
data=np.array([1,2,3,4,5])
## Calculate mean
print(np.mean(data))
## Calculate median
print(np.median(data))
## Calculate standard deviation
print(np.std(data))
## Normalize the data
print(np.linalg.norm(data))

3.0
3.0
1.4142135623730951
7.416198487095663


In [32]:
#Logical operations
arr1=np.array([1,2,3,4,5])
arr1>3

array([False, False, False,  True,  True])

In [33]:
data[(data>3) & (data<7)]

array([4, 5])